using Abilities;
using UnityEngine;
using UnityEngine.UI;

public class BlackDieAbility: StartingBlackDieAbility
{
    protected override void OnEnable()
    {
        base.OnEnable();
        ChestRewardSelection.BlackDiceAbilitySelected += HandleBlackDieAbilityGained;
    }

    protected override void OnDisable()
    {
        base.OnDisable();
        ChestRewardSelection.BlackDiceAbilitySelected -= HandleBlackDieAbilityGained;
    }
    
    private void HandleBlackDieAbilityGained()
    {
        abilityUseOne.GetComponent<Button>().interactable = true;
        abilityUseTwo.GetComponent<Button>().interactable = true;
        abilityUseThree.GetComponent<Button>().interactable = true;
    }
}
